name: Welcome New Contributor

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations on opening your first issue to the project! We will triage this shortly.'
          pr-message: 'Congratulations on opening your first pull request to the project! A core maintainer will review your contribution shortly.'
