name: Import open source standard labels

on:
  push:
    branches: [main]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: j-dogcoder/gh-action-labels@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner-name: ${{ github.repository_owner }}
          repository-name:
            ${{ github.event.repository.name }}
            # force: true # optional to clear existing labels, default to false
